In [2]:
import sys
sys.path.append('../unseen')

import xarray as xr
import numpy as np

import myfuncs

In [3]:
infile = '/g/data/xv83/ds0092/CAFE/forecasts/f6/WIP/c5-d60-pX-f6-19931101/ZARR/atmos_isobaric_month.zarr.zip'

In [4]:
cafe_kwargs = {'metadata_file': '../config/dataset_cafe.yml',
               'no_leap_days': True,
               'region': 'TAS-POINT',
               'variables': ['pr'],
               'units' : {'pr': 'mm/day'},
              }

In [5]:
ds = myfuncs.open_file(infile, **cafe_kwargs)
ds

<xarray.Dataset>
Dimensions:   (ensemble: 96, time: 120)
Coordinates:
  * ensemble  (ensemble) int64 1 2 3 4 5 6 7 8 9 ... 88 89 90 91 92 93 94 95 96
  * time      (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00
Data variables:
    pr        (time, ensemble) float32 dask.array<chunksize=(24, 96), meta=np.ndarray>
Attributes:
    comment:    pressure level interpolator, version 3.0, precision=double
    filename:   atmos_isobaric_month.zarr
    grid_tile:  N/A
    grid_type:  regular
    title:      AccessOcean-AM2

In [5]:
days_in_month = ds.time.dt.days_in_month

## Annual

In [6]:
days_in_year = days_in_month.groupby('time.year').sum().values

In [7]:
days_in_year

array([ 61, 365, 365, 366, 365, 365, 365, 366, 365, 365, 304])

In [8]:
years = ds.indexes['time'].year
unique_years = np.unique(years)

In [9]:
unique_years

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003])

In [10]:
days_in_unique_years = {unique_years[i]: days_in_year[i] for i in range(len(unique_years))}

In [11]:
days_in_unique_years

{1993: 61,
 1994: 365,
 1995: 365,
 1996: 366,
 1997: 365,
 1998: 365,
 1999: 365,
 2000: 366,
 2001: 365,
 2002: 365,
 2003: 304}

In [12]:
days_in_year = np.array([days_in_unique_years[yr] for yr in years])

In [13]:
days_in_year

array([ 61,  61, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 366, 366, 366, 366,
       366, 366, 366, 366, 366, 366, 366, 366, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 304, 304, 304, 304, 304, 304, 304,
       304, 304, 304])

In [14]:
annual_fraction = days_in_month / days_in_year

In [15]:
annual_fraction

<xarray.DataArray 'days_in_month' (time: 120)>
array([0.49180328, 0.50819672, 0.08493151, 0.07671233, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08493151,
       0.07671233, 0.08493151, 0.08219178, 0.08493151, 0.08219178,
       0.08493151, 0.08493151, 0.08219178, 0.08493151, 0.08219178,
       0.08493151, 0.08469945, 0.07923497, 0.08469945, 0.08196721,
       0.08469945, 0.08196721, 0.08469945, 0.08469945, 0.08196721,
       0.08469945, 0.08196721, 0.08469945, 0.08493151, 0.07671233,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.08493151, 0.07671233, 0.08493151, 0.08219178, 0.08493151,
       0.08219178, 0.08493151, 0.08493151, 0.08219178, 0.08493151,
       0.08219178, 0.08493151, 0.08493151, 0.07671233, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08469945,
       0.07923497, 0.08469945, 0.08196721, 0.08469945, 0.08196721,
       0.08469945, 0.08469945, 0.08196721, 0.08469945, 0.08196721,
       0.08469945, 0.08493151, 0.07671233, 0.08493151, 0.08219178,
       0.08493151, 0.08219178, 0.08493151, 0.08493151, 0.08219178,
       0.08493151, 0.08219178, 0.08493151, 0.08493151, 0.07671233,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.10197368, 0.09210526, 0.10197368, 0.09868421, 0.10197368,
       0.09868421, 0.10197368, 0.10197368, 0.09868421, 0.10197368])
Coordinates:
  * time     (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00

In [19]:
np.testing.assert_allclose(annual_fraction.groupby('time.year').sum().min(), 1.0)
np.testing.assert_allclose(annual_fraction.groupby('time.year').sum().max(), 1.0)

In [ ]:
#ube.data = cube.data * weights_array
#    cube = cube.aggregated_by(['year'], iris.analysis.SUM)

In [21]:
ds * annual_fraction

<xarray.Dataset>
Dimensions:   (ensemble: 96, time: 120)
Coordinates:
  * ensemble  (ensemble) int64 1 2 3 4 5 6 7 8 9 ... 88 89 90 91 92 93 94 95 96
  * time      (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00
Data variables:
    pr        (time, ensemble) float64 dask.array<chunksize=(24, 96), meta=np.ndarray>

In [23]:
(ds * annual_fraction).resample(time='A-DEC').sum()

<xarray.Dataset>
Dimensions:   (ensemble: 96, time: 11)
Coordinates:
  * time      (time) object 1993-12-31 00:00:00 ... 2003-12-31 00:00:00
  * ensemble  (ensemble) int64 1 2 3 4 5 6 7 8 9 ... 88 89 90 91 92 93 94 95 96
Data variables:
    pr        (time, ensemble) float64 dask.array<chunksize=(1, 96), meta=np.ndarray>

## Seasonal

In [52]:
months = ds.indexes['time'].month
months

array([11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,
        4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10])

In [41]:
days_in_month = ds['time'].dt.days_in_month

In [42]:
days_in_month

<xarray.DataArray 'days_in_month' (time: 120)>
array([30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31,
       30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 29, 31, 30, 31, 30, 31, 31,
       30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31,
       28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30,
       31, 31, 30, 31, 30, 31, 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30,
       31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30,
       31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30,
       31])
Coordinates:
  * time     (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00

In [54]:
start_month = months[0]
start_month

11

In [55]:
end_month = months[-1]
end_month

10

In [56]:
rolling_sum = days_in_month.rolling({'time': 3}, min_periods=1).sum()
rolling_sum

<xarray.DataArray 'days_in_month' (time: 120)>
array([30., 61., 92., 90., 90., 89., 92., 91., 92., 92., 92., 92., 91.,
       92., 92., 90., 90., 89., 92., 91., 92., 92., 92., 92., 91., 92.,
       92., 91., 91., 90., 92., 91., 92., 92., 92., 92., 91., 92., 92.,
       90., 90., 89., 92., 91., 92., 92., 92., 92., 91., 92., 92., 90.,
       90., 89., 92., 91., 92., 92., 92., 92., 91., 92., 92., 90., 90.,
       89., 92., 91., 92., 92., 92., 92., 91., 92., 92., 91., 91., 90.,
       92., 91., 92., 92., 92., 92., 91., 92., 92., 90., 90., 89., 92.,
       91., 92., 92., 92., 92., 91., 92., 92., 90., 90., 89., 92., 91.,
       92., 92., 92., 92., 91., 92., 92., 90., 90., 89., 92., 91., 92.,
       92., 92., 92.])
Coordinates:
  * time     (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00

In [57]:
if start_month in [2, 5, 8, 11]:
    start_index = 0
elif start_month in [1, 4, 7, 10]:
    start_index = 1
elif start_month in [12, 3, 6, 9]:
    start_index = 2

days_per_season = rolling_sum[start_index::3]
days_per_season

<xarray.DataArray 'days_in_month' (time: 40)>
array([30., 90., 92., 92., 91., 90., 92., 92., 91., 91., 92., 92., 91.,
       90., 92., 92., 91., 90., 92., 92., 91., 90., 92., 92., 91., 91.,
       92., 92., 91., 90., 92., 92., 91., 90., 92., 92., 91., 90., 92.,
       92.])
Coordinates:
  * time     (time) object 1993-11-16 00:00:00 ... 2003-08-16 12:00:00

In [58]:
days_in_season = np.repeat(days_per_season.values[1:], 3)
days_in_season

array([90., 90., 90., 92., 92., 92., 92., 92., 92., 91., 91., 91., 90.,
       90., 90., 92., 92., 92., 92., 92., 92., 91., 91., 91., 91., 91.,
       91., 92., 92., 92., 92., 92., 92., 91., 91., 91., 90., 90., 90.,
       92., 92., 92., 92., 92., 92., 91., 91., 91., 90., 90., 90., 92.,
       92., 92., 92., 92., 92., 91., 91., 91., 90., 90., 90., 92., 92.,
       92., 92., 92., 92., 91., 91., 91., 91., 91., 91., 92., 92., 92.,
       92., 92., 92., 91., 91., 91., 90., 90., 90., 92., 92., 92., 92.,
       92., 92., 91., 91., 91., 90., 90., 90., 92., 92., 92., 92., 92.,
       92., 91., 91., 91., 90., 90., 90., 92., 92., 92., 92., 92., 92.])

In [59]:
if start_month in [2, 5, 8, 11]:
    days_in_season = np.insert(days_in_season, 0, rolling_sum[0])
elif start_month in [1, 4, 7, 10]:
    days_in_season = np.insert(days_in_season, 0, rolling_sum[0:2])

In [60]:
if end_month in [1, 4, 7, 10]:
    final_season = days_in_month[-1] + days_in_month[-2]
    days_in_season = np.append(days_in_season, [final_season, final_season])
elif end_month in [12, 3, 6, 9]:
    days_in_season = np.append(days_in_season, days_in_month[-1])

In [61]:
days_in_season

array([30., 90., 90., 90., 92., 92., 92., 92., 92., 92., 91., 91., 91.,
       90., 90., 90., 92., 92., 92., 92., 92., 92., 91., 91., 91., 91.,
       91., 91., 92., 92., 92., 92., 92., 92., 91., 91., 91., 90., 90.,
       90., 92., 92., 92., 92., 92., 92., 91., 91., 91., 90., 90., 90.,
       92., 92., 92., 92., 92., 92., 91., 91., 91., 90., 90., 90., 92.,
       92., 92., 92., 92., 92., 91., 91., 91., 91., 91., 91., 92., 92.,
       92., 92., 92., 92., 91., 91., 91., 90., 90., 90., 92., 92., 92.,
       92., 92., 92., 91., 91., 91., 90., 90., 90., 92., 92., 92., 92.,
       92., 92., 91., 91., 91., 90., 90., 90., 92., 92., 92., 92., 92.,
       92., 61., 61.])

In [62]:
days_in_season.shape

(120,)

## New function

In [5]:
ds

<xarray.Dataset>
Dimensions:   (ensemble: 96, time: 120)
Coordinates:
  * ensemble  (ensemble) int64 1 2 3 4 5 6 7 8 9 ... 88 89 90 91 92 93 94 95 96
  * time      (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00
Data variables:
    pr        (time, ensemble) float32 dask.array<chunksize=(24, 96), meta=np.ndarray>
Attributes:
    comment:    pressure level interpolator, version 3.0, precision=double
    filename:   atmos_isobaric_month.zarr
    grid_tile:  N/A
    grid_type:  regular
    title:      AccessOcean-AM2

In [6]:
myfuncs.temporal_aggregation(ds, 'Q-NOV', 'mean', input_freq='M')

> /home/599/dbi599/unseen/unseen/myfuncs.py(209)monthly_to_seasonal_mean()
    207     """Monthly to seasonal mean"""
    208     pdb.set_trace()
--> 209     days_in_seas = days_in_season(ds)
    210     days_in_mon = ds['time'].dt.days_in_month
    211     season_fraction = days_in_mon / days_in_seas

ipdb> n
> /home/599/dbi599/unseen/unseen/myfuncs.py(210)monthly_to_seasonal_mean()
    208     pdb.set_trace()
    209     days_in_seas = days_in_season(ds)
--> 210     days_in_mon = ds['time'].dt.days_in_month
    211     season_fraction = days_in_mon / days_in_seas
    212     np.testing.assert_allclose(nested_groupby_apply(season_fraction, ['time.year', 'time.season'], np.min), 1.0)

ipdb> days_in_seas
array([30., 31., 90., 90., 92., 92., 92., 92., 92., 92., 91., 91., 91.,
       90., 90., 90., 92., 92., 92., 92., 92., 92., 91., 91., 91., 90.,
       91., 91., 92., 92., 92., 92., 92., 92., 91., 91., 91., 91., 90.,
       90., 92., 92., 92., 92., 92., 92., 91., 91., 91., 90., 90., 90.,

BdbQuit: 