In [23]:
import sys
sys.path.append('../unseen')

import xarray as xr
import numpy as np

import myfuncs

In [4]:
infile = '/g/data/xv83/ds0092/CAFE/forecasts/f6/WIP/c5-d60-pX-f6-19931101/ZARR/atmos_isobaric_month.zarr.zip'

In [5]:
cafe_kwargs = {'metadata_file': '../config/dataset_cafe.yml',
               'no_leap_days': True,
               'region': 'TAS-POINT',
               'variables': ['pr'],
               'units' : {'pr': 'mm/day'},
              }

In [6]:
ds = myfuncs.open_file(infile, **cafe_kwargs)
ds

<xarray.Dataset>
Dimensions:   (ensemble: 96, time: 120)
Coordinates:
  * ensemble  (ensemble) int64 1 2 3 4 5 6 7 8 9 ... 88 89 90 91 92 93 94 95 96
  * time      (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00
Data variables:
    pr        (time, ensemble) float32 dask.array<chunksize=(24, 96), meta=np.ndarray>
Attributes:
    comment:    pressure level interpolator, version 3.0, precision=double
    filename:   atmos_isobaric_month.zarr
    grid_tile:  N/A
    grid_type:  regular
    title:      AccessOcean-AM2

In [8]:
days_in_month = ds.time.dt.days_in_month

In [27]:
days_in_year = days_in_month.groupby('time.year').sum().values

In [28]:
days_in_year

array([ 61, 365, 365, 366, 365, 365, 365, 366, 365, 365, 304])

In [39]:
years = ds.indexes['time'].year
unique_years = np.unique(years)

In [40]:
unique_years

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003])

In [44]:
days_in_unique_years = {unique_years[i]: days_in_year[i] for i in range(len(unique_years))}

In [45]:
days_in_unique_years

{1993: 61,
 1994: 365,
 1995: 365,
 1996: 366,
 1997: 365,
 1998: 365,
 1999: 365,
 2000: 366,
 2001: 365,
 2002: 365,
 2003: 304}

In [47]:
days_in_year = np.array([days_in_unique_years[yr] for yr in years])

In [48]:
days_in_year

array([ 61,  61, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 366, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 366, 366, 366, 366,
       366, 366, 366, 366, 366, 366, 366, 366, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365, 365,
       365, 365, 365, 365, 365, 365, 304, 304, 304, 304, 304, 304, 304,
       304, 304, 304])

In [49]:
annual_fraction = days_in_month / days_in_year

In [50]:
annual_fraction

<xarray.DataArray 'days_in_month' (time: 120)>
array([0.49180328, 0.50819672, 0.08493151, 0.07671233, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08493151,
       0.07671233, 0.08493151, 0.08219178, 0.08493151, 0.08219178,
       0.08493151, 0.08493151, 0.08219178, 0.08493151, 0.08219178,
       0.08493151, 0.08469945, 0.07923497, 0.08469945, 0.08196721,
       0.08469945, 0.08196721, 0.08469945, 0.08469945, 0.08196721,
       0.08469945, 0.08196721, 0.08469945, 0.08493151, 0.07671233,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.08493151, 0.07671233, 0.08493151, 0.08219178, 0.08493151,
       0.08219178, 0.08493151, 0.08493151, 0.08219178, 0.08493151,
       0.08219178, 0.08493151, 0.08493151, 0.07671233, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08493151,
       0.08219178, 0.08493151, 0.08219178, 0.08493151, 0.08469945,
       0.07923497, 0.08469945, 0.08196721, 0.08469945, 0.08196721,
       0.08469945, 0.08469945, 0.08196721, 0.08469945, 0.08196721,
       0.08469945, 0.08493151, 0.07671233, 0.08493151, 0.08219178,
       0.08493151, 0.08219178, 0.08493151, 0.08493151, 0.08219178,
       0.08493151, 0.08219178, 0.08493151, 0.08493151, 0.07671233,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.08493151, 0.08219178, 0.08493151, 0.08219178, 0.08493151,
       0.10197368, 0.09210526, 0.10197368, 0.09868421, 0.10197368,
       0.09868421, 0.10197368, 0.10197368, 0.09868421, 0.10197368])
Coordinates:
  * time     (time) object 1993-11-16 00:00:00 ... 2003-10-16 12:00:00